version: '3.9'

services:
  user-db:
    image: postgres:16
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data

volumes:
  ecommerce-db-data: